# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:02
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gladiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('points', models.FloatField()),
                ('round', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('round', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Player')),
            ],
        ),
        migrations.AddField(
            model_name='gladiator',
            name='gladiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Player'),
        ),
        migrations.AddField(
            model_name='dailyloser',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Player'),
        ),
    ]
