# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_auto_20160429_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Gladiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('points', models.FloatField()),
                ('gladiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.Player')),
            ],
        ),
        migrations.AlterField(
            model_name='throw',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 19, 38, 43, 243080, tzinfo=utc)),
        ),
    ]
