# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0005_auto_20160531_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 5, 12, 50, 3, 56000, tzinfo=utc)),
        ),
    ]
