# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0007_auto_20160605_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='throw',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='throw',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 20, 15, 49, 634000, tzinfo=utc)),
        ),
    ]
