# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0018_auto_20160612_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
