# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bb', '0019_auto_20160612_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
    ]
