# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bb', '0021_player_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throw',
            options={'get_latest_by': 'event_time'},
        ),
        migrations.AlterField(
            model_name='throw',
            name='result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='throw',
            name='round',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
