# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bb', '0022_auto_20170209_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='result',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='throw',
            name='round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
