# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bb', '0023_auto_20170209_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyloser',
            name='round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gladiator',
            name='round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
